dist: trusty

language: ruby

addons:
  apt:
    packages:
      - python3

install:
  - git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - brew install mecab mecab-ipadic

script:
  - LD_LIBRARY_PATH="$HOME/.linuxbrew/lib" rake
